### ISSUE TITLE
Typo on Screenshots | Generate KeyShares

### ISSUE THREAD

**Issue by BenAffleck** [stakestar/starkeys#3]
Hi, wonderful work! 

There's a typo at stage 3 'Generate KeyShares', at least on the screenshots, probably also in the resource files.
https://github.com/stakestar/starkeys/blob/e985f3ac96024d87f6f7528dad5556ae3f373d36/README.md

![image](https://user-images.githubusercontent.com/92367515/212103185-9105960f-8d44-44ff-a100-09238ee1423f.png)

**Comment by arsoba** [comment]
Thanks @BenAffleck 

This type fixed in new release.
