### ISSUE TITLE
Input arguments not parsed 

### ISSUE THREAD

**Issue by Yonatank88** [stakestar/starkeys#4]
When using input arguments from the webapp only the owner address is parsed:

Argument used
`--operator-keys=LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNWVUNUwwV0h6ZTdyTWZPb2xtVHMKdWtIQ2E4K3dtbUw2OTFJQ1RpREE1UkJ1TkxqSVQ2WkE0YzMxcVRIY3FBVHl5eVkwLzk3R3lKZ2doYnlFR2RoZQovalh6aWVTOXJ2RytJVGF1QjhMVlhkekxGYVQxWEZWeFlnN2x2TlB4OURPL1ZoRkhkWWxnT3I2d0RtV3FjRGo3ClhWUWFOWEFtRng3NjVQNTlXNXZzVGRXVWFHRWxXSm93SkZKdnc2UlRISkZ1TVhjSzZVaWJ0cUZMSmJwOW5kdUgKQjlLSzNWcmYrZmtJOWRBZ2txRDFHOElxQ0tKMVl3bjUyeGxxbTRCNitOOGZUZE1MS1JucWpFZmRzV1dwMFVzMQpLTW9vSXcyc3BoaXAzUFpNYnJaaU0wNjJ2ZUo0U3ovYjBObWdPTnhTd0JJTnNxcG54QjhFUVQxSTNjNklqNXhhCm5RSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K,LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNmNwM0g3cG5XNEhEOW9JTis2TzgKTG0wWXFHYWhDakFBRjYyUnVOM2UySmk3TGpIQytMWDhuSHByYkxwbjRKYUIrQmhXTk9KTCtUdXhpem9RUFp1awp2bkZyd2YrblVyemdKTHl4WXNsSWhJajhxNVRaRnpiMldmMXhQQW9pNE04WWhJdzNoRitQeXlacjROU2tnakpnCk1tQWJ5YjFYRHpFYWYrZTVCN0I4Tk1iTXRmK3crZHRFMHNQZVhZWVJJaGt1eGRqbkdwV2I5TUtZK1MrWGhXamEKR2wzRURzSkVDUlVGNk4zclYzSStXL1UvdUVaWUNtTGo1eWozYlM1NFdSS2hZbnJWMWJKcWhhSkhaRVN0Vi9HQwo0cTBOZU1vbFFsRXRvSmZ6aHdmcHpoL2N2N3kxUXMvQ0RQb2JmUGNnVVU4eXhMelR6ZnNyTzgzaVRZQnF0YWNyClVRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K,LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdVVJVXBQVDRRc05BMlpUL2FZNFAKakxUNGpCTzFTUGw4TUJpRmg2b3Fmd2xwVTRzYVM5KzRkd2Fjd2cvOHpZWUt5QW5Eb0ltNWc3ZnV6a1VoSjhrVQpSUlNoaUxTczBkUUMxRVE5WU5nUjdlZWlwSVBEN3Q1N0kxR3FHYk1uK0R4amtYOWRRT0thSHRzVUxIOTB5aEpXCi9WVGRtSkxVSFRvZTQxOXdieER6cXh1YXQ0Q0JxSjZWamxLdHA1UC9COFI0WnlBMzc2ajh2QVZYc0Q3SjVFUHQKK3FLK2hteXZ6czU0NlQySDc0Z0IzSCtOeVFrMGJJbDRUQ3dHMFBTOUNETkpuRFFDaHVUT3RXcXpxbDN5MlZIRQoyNmc0Rkg4QW5YODFoQ0MyenRCMUd0elBFcjBBRW1IdzJqdXFuZVlYNVNQbXRoV1BMOENLdUFPeXRuK01neUw3CnR3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K,LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcEs0bThhR2JNaFRVMGdZS0sxMVYKZTJrT093ZFRYeXJZT2t1U0tyTWpyeFp2TTRnNnM5OW5XQ0x2N1dPZkZ2Wm9RQ0pONDFETHdoTWh0OU82cFFEdQo2bjYrMWpOemhKbDhWYkRIakwzNnk0MEozcXdreDlxVk5MSDEzWGVCTTVCak91UUJSeFJFU3lWV1N1VnJwQjdFCnJCZnRnL1ZMYzJsZ1FJSkZXcHBMajBpNzcweGxkWXdRdFlwcHFBakViaHZ5Vk1NRzUrUGM4a0psNFhkQldJcHQKWnJvK0dKcEhma3ZuZE1NM2I2VTR3ZVdrZHltR2FpdVVSTzEwWFJpdmVCMDI0T3ppa0NYbGVGUkhxSzRvMUN1RgpzcldhNDVISVhLSUFiNXVkY3luVG5GbHhIa3ZkenRhRUNEcFF5ay9nSVdvbzNia3pxK29pUVhXd2tVUGt6ajNZCnNRSURBUUFCCi0tLS0tRU5EIFtTQSBQVUJMSUMgS0VZLS0tLS0K --operator-ids=3,6,8,9 --owner-address=0x4063657629f08f43aaf37358ffb0e4636d1dcb0c --owner-nonce=9`

![image](https://github.com/stakestar/starkeys/assets/94914141/c8344f8a-102a-410b-98e6-062675a1718d)

Operator fields, Nonce field stay empty

**Comment by arsoba** [comment]
Fixed in [v0.3.2](https://github.com/stakestar/starkeys/releases/tag/v0.3.2)

**Comment by arsoba** [comment]
Fixed in [v0.3.2](https://github.com/stakestar/starkeys/releases/tag/v0.3.2)
